### ISSUE TITLE
ISSUE N27: Actualización de ramas

### ISSUE THREAD

**Issue by Gisemariananadaya** [PPROF1-2021/g7-a3g7helpu#42]
Actualizar todas las ramas del proyecto para no generar inconsistencia.

**Comment by MicaMontali** [comment]
Ramas: 
- DesarrolladorMicaela
- desarrolladorMica
- MicaDesarrollador 
Actualizadas. En las siguientes entregas continuaré trabajando solo en DesarrolladorMicaela para no generar confusión pero no borro las otras dos para que no se generen conflictos con el trabajo ya realizado.
