### ISSUE TITLE
ISSUE N32: Validación de campos vacíos

### ISSUE THREAD

**Issue by Gisemariananadaya** [PPROF1-2021/g7-a3g7helpu#50]
- Validación de campos vacíos mediante Bootstrap (de acuerdo al template de la web oficial)
- luego con Javascript la longitud de los campos, tipo de datos en los input. Los campos nombre y apellido deberán validarse con más de 2 caracteres.

**Comment by MicaMontali** [comment]
Se creó la validación de campos vacíos en el formulario de contacto y se lo ancló con el botón de formulario enviado, para que al completar todo solamente se puedan enviar los datos
