### ISSUE TITLE
ISSUE N33: Crear una función en JavaScript (fechas)

### ISSUE THREAD

**Issue by Gisemariananadaya** [PPROF1-2021/g7-a3g7helpu#51]
Crear una función en JavaScript para mostrar un cálculo de fechas (edad, día de turno, u otro pertinente al proyecto en desarrollo).

**Comment by MicaMontali** [comment]
Se creó una función con java Sript para mostrar la fecha actualizada en la que el usuario navega en ella, ubicada al finalizar la página(footer).
